### PR TITLE
Published the package on crates.io

### PR DESCRIPTION
**Pull request by jaiakash**
Hi, I published the tuxfetch package on crates.io :+1:
Link : https://crates.io/crates/tuxfetch 
Issue #4

### CODE REVIEW

**Comment by wiredhikari** [comment]
> Hi, I published the tuxfetch package on crates.io +1 Link : https://crates.io/crates/tuxfetch Issue #4

cool, make me owner of the crate, need to change readme

**Comment by jaiakash** [comment]
Invited you to become the owner. :1st_place_medal: 

>need to change readme

Can you tell what to add? :+1:

**Comment by wiredhikari** [comment]
> Invited you to become the owner. 1st_place_medal
> 
> > need to change readme
> 
> Can you tell what to add? +1

Usage and flag instructions, I will need owner access to modify it.

**Comment by jaiakash** [comment]
> I will need owner access to modify it.

Yeah Atharva, I have sent the owner request to you on crates.io website. Check your dashboard on crates.io
If there is no request, just message me I would send the request again.

**Comment by wiredhikari** [comment]
Thanks

**Pull request merged**
